services:
  db:
    image: postgres:16-alpine
    container_name: inventicore_db
    environment:
      POSTGRES_USER: inventicore
      POSTGRES_PASSWORD: inventicore_dev_2024
      POSTGRES_DB: inventicore_db
    ports:
      - "5433:5432"
    volumes:
      - inventicore_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: inventicore_rmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: inventicore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: src/InventiCore.Api/Dockerfile
    container_name: inventicore_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=inventicore_db;Username=inventicore;Password=inventicore_dev_2024
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - Redis__ConnectionString=redis:6379
    ports:
      - "5030:8080"
    depends_on:
      - db
      - rabbitmq
      - redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: src/InventiCore.Web/Dockerfile
    container_name: inventicore_web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  inventicore_pgdata:
